name: TorchBench PR Test
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  CONDA_ENV: "torchbench"
  SETUP_SCRIPT: "/workspace/setup_instance.sh"

jobs:
  pr-test:
    runs-on: [self-hosted, a100-runner]
    timeout-minutes: 1440 # 24 hours
    steps:
      - name: Checkout TorchBench
        uses: actions/checkout@v3
      - name: GPU Tuning
        run: |
          sudo nvidia-smi -pm 1
          sudo nvidia-smi -ac 1215,1410
          nvidia-smi
      - name: Install TorchBench
        run: |
          bash ./scripts/torchbench_install.sh
      - name: Validate benchmark components
        run: |
          bash ./scripts/torchbench_test.sh

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
